*** S/P PUSHOPT - SERT A SAUVER LES VALEURS DES OPTIONS DE OPTN
#include "aaaamac.cdk"
*
      SUBROUTINE PUSHOPT
#include "impnone.cdk"
*
*AUTEURS       M. LEPINE  -  PRINTEMPS 85
*
*REVISION 001 Y. BOURASSA - MAI 94 RATFOR @ FTN77
*
*LANGUAGE   - FTN77
*
*OBJET(PUSHOPT)
*     SERT A SAUVER LES OPTIONS DU COMMON PARAMS A L'APPEL D'UN SEGMENT
*
*MODULES
      EXTERNAL DFLERMS, TTTPWI1
**
#include "params.cdk"

      INTEGER  I
      
      OPTSTCK = OPTSTCK + 1
      WRITE(77, REC=OPTSTCK) (TABOPT(I),I=1,100)
      RETURN


      ENTRY POPOPT
*     SERT A REOBTENIR LES OPTIONS DU COMMON PARAMS AU RETOUR D'UN
*     SEGMENT
      IF(OPTSTCK .LE. BASLOPT) THEN
         WRITE(6,*)' POPOPT TENTATIVE DE POP AVEC OPTSTCK <= BASLOPT'
      ELSE
         READ(77,REC=OPTSTCK) (TABOPT(I),I=1,100)
         OPTSTCK = OPTSTCK - 1
      ENDIF

      CALL TTTPWI1

      RETURN
      END
