#if defined(__flang__)
      subroutine idate(z)
      integer z(3), t(8)
      call date_and_time(values=t)
      z(1) = t(3)    ! day
      z(2) = t(2)    ! month
      z(3) = t(1)    ! year
      return
      end
#endif
#if defined (RASTER) 
#if defined (CRAY) 
*** S/P TTTBAN - CONSTRUIRE LA BANNIERE DU GRAPHIQUE
#include "aaaamac.cdk"
*
      SUBROUTINE TTTBAN(USAGER, JOBN, CDATE, CTIME, TNAME, PROTOCL)
#include "impnone.cdk"
      CHARACTER * 8     USAGER, JOBN, CDATE, CTIME, TNAME, PROTOCL
*
*AUTEUR       M. LEPINE
*
*REVISION 001 Y. BOURASSA - MAI 94 RATFOR @ FTN77
*
*LANGUAGE   - FTN77
*
*OBJET(TTTBAN)
*     SERT A CONSTRUIRE LA BANNIERE (PREMIERE PAGE DU GRAPHIQUE) SERVANT
* D'IDENTIFICATION.  LES INFORMATIONS CONTENUS SONT :
*                    - LE CODE DE L'USAGER
*                    - LE NOM DU TRAVAIL SOUMIS
*                    - LA DATE DU DEBUT D'EXECUTION
*                    - L'HEURE DU DEBUT D'EXECUTION
*
*ARGUMENTS
*   OUT   USAGER    CODE LE L'USAGER
*   OUT   JOBN      NOM DU TRAVAIL SOUMIS
*   OUT   CDATE     DATE DE L'EXECUTION DU TRAVAIL
*   OUT   CTIME     TEMPS DE L'EXECUTION DU TRAVAIL
*   IN    TNAME     NOM DU TRAVAIL (FOURNI PAR L'USAGER)
*
*MODULES
      EXTERNAL UNPACK, CLOCK, DATE, ACTTABLE, RNB, ASC2DSC, WRITE
*
**
      COMMON/QQQTACC/ IUCOD,IJSN
      INTEGER IUCOD, IJSN
      CHARACTER * 4 USR
      CHARACTER * 64 CBUF
      INTEGER  I, DAT, HEURE, JCB, JAC(0:36), RNB, BUFFER(7), ID(8),
     +         USER, JOBNAME, DATE, TIME
      POINTER (REFADR,JCB(0:127))
*
#include "params.cdk"
#include "lnkpak.cdk"
#include "mesgid.cdk"
*
      CALL ACTTABLE(JAC,37)
      REFADR = 0
      USER   = RNB(JAC(6) .AND. MASK(56))
      WRITE(USAGER,'(A8)') USER
      JOBNAME = RNB(JCB(64))
      IF(TNAME .ne. ' ') READ(TNAME,'(A8)') JOBNAME
      IF(USAGER(1:4) .eq. 'ARMN') then
         USR(1:4) = '-'//USAGER(5:7)
      ELSE
         USR(1:4) = USAGER(1:4)
      ENDIF
      READ(USR,'(A4)') COMPTAB(1)
      COMPTAB(1) = COMPTAB(1) .AND. MASK(32)
      WRITE(IPUNIT,'(///T30,"IDENTIFICATION")')
      WRITE(IPUNIT,'(/T10,A8)') USER
      WRITE(IPUNIT,'(/T10,A8)') JOBNAME
      CALL DATE( DAT )
      CALL CLOCK( HEURE )
      IF(PROTOCL .EQ. 'LINK') WRITE(MESSAGE,'(4A8)') USER, JOBNAME,
     +                              DAT, HEURE
      WRITE(IPUNIT,'(/T10,A8)') DAT
      WRITE(IPUNIT,'(/T10,A8)') HEURE
      ID(1) = "        "
      ID(2) = USER
      ID(3) = "        "
      ID(4) = JOBNAME
      ID(5) = "        "
      ID(6) = DAT
      ID(7) = "        "
      ID(8) = HEURE
      CALL ASC2DSC(ID,BUFFER)
      IF(PROTOCL .EQ. 'KMW') THEN
         CALL WRITE('RAZZ2'L,BUFFER,7,28)
         WRITE(LJUST(RAZZ3)) ID
      ENDIF
      WRITE(JOBN,  '(A8)') JOBNAME
      WRITE(CDATE, '(A8)') DAT
      WRITE(CTIME, '(A8)') HEURE

      RETURN
      END
#endif
#if defined (SUN) 
*** S/P TTTBAN - CONSTRUIRE LA BANNIERE DU GRAPHIQUE
#include "aaaamac.cdk"
*
      SUBROUTINE TTTBAN(USAGER, JOBN, CDATE, CTIME, TNAME, PROTOCL)
#include "impnone.cdk"
      CHARACTER*8       USAGER, JOBN, CDATE, CTIME, TNAME, PROTOCL
*
*AUTEUR       M. LEPINE
*
*REVISION 001 Y. BOURASSA - MAI 94 RATFOR @ FTN77
*
*LANGUAGE   - FTN77
*
*OBJET(TTTBAN)
*     SERT A CONSTRUIRE LA BANNIERE (PREMIERE PAGE DU GRAPHIQUE) SERVANT
* D'IDENTIFICATION.  LES INFORMATIONS CONTENUS SONT :
*                    - LE CODE DE L'USAGER
*                    - LE NOM DU TRAVAIL SOUMIS
*                    - LA DATE DU DEBUT D'EXECUTION
*                    - L'HEURE DU DEBUT D'EXECUTION
*
*ARGUMENTS
*   OUT   USAGER    CODE LE L'USAGER
*   OUT   JOBN      NOM DU TRAVAIL SOUMIS
*   OUT   CDATE     DATE DE L'EXECUTION DU TRAVAIL
*   OUT   CTIME     TEMPS DE L'EXECUTION DU TRAVAIL
*   IN    TNAME     NOM DU TRAVAIL (FOURNI PAR L'USAGER)
*
**
      CHARACTER * 24 FDATE,FULLDAT
      CHARACTER * 8  TIME
      INTEGER IDAT(3)
*
#include "params.cdk"
#include "lnkpak.cdk"
#include "mesgid.cdk"
*
*MODULE
      EXTERNAL IDATE, GETENVC

      MESSAGE = ' '
      CALL GETENVC('USER',USAGER)
      JOBN    = USAGER
      FULLDAT = FDATE()
      CALL IDATE( IDAT )
      WRITE(CDATE,55) IDAT(1),'/',IDAT(2),'/',MOD(IDAT(3),100)
 55   FORMAT(I2.2,A1,I2.2,A1,I2.2)
      CTIME = FULLDAT(12:19)
      IF(TNAME   .NE. ' ')    JOBN = TNAME
      IF(PROTOCL .EQ. 'LINK') WRITE(MESSAGE,'(4A8)') USAGER, JOBN,
     +                              CDATE, CTIME
      WRITE(IPUNIT,'(///T30,"IDENTIFICATION")')
      WRITE(IPUNIT,'(/T10,A8)') USAGER
      WRITE(IPUNIT,'(/T10,A8)') JOBN
      WRITE(IPUNIT,'(/T10,A15)') FULLDAT(1:11)//FULLDAT(21:24)
      WRITE(IPUNIT,'(/T10,A8)') CTIME
      IF(PROTOCL .EQ. 'KMW') WRITE(99,77) USAGER, JOBN, CDATE, CTIME
 77   FORMAT(8X, A8, 8X, A8, 8X, A10, 8X, A8)

      RETURN
      END
#endif
#if defined (C910)
*** S/P TTTBAN - CONSTRUIRE LA BANNIERE DU GRAPHIQUE
#include "aaaamac.cdk"
*
      SUBROUTINE TTTBAN(USAGER, JOBN, CDATE, CTIME, TNAME, PROTOCL)
#include "impnone.cdk"
      CHARACTER * 8     USAGER, JOBN, CDATE, CTIME, TNAME, PROTOCL
*
*AUTEUR       M. LEPINE
*
*REVISION 001 Y. BOURASSA - MAI 94 RATFOR @ FTN77
*
*LANGUAGE   - FTN77
*
*OBJET(TTTBAN)
*     SERT A CONSTRUIRE LA BANNIERE (PREMIERE PAGE DU GRAPHIQUE) SERVANT
* D'IDENTIFICATION.  LES INFORMATIONS CONTENUS SONT :
*                    - LE CODE DE L'USAGER
*                    - LE NOM DU TRAVAIL SOUMIS
*                    - LA DATE DU DEBUT D'EXECUTION
*                    - L'HEURE DU DEBUT D'EXECUTION
*
*ARGUMENTS
*   OUT   USAGER    CODE LE L'USAGER
*   OUT   JOBN      NOM DU TRAVAIL SOUMIS
*   OUT   CDATE     DATE DE L'EXECUTION DU TRAVAIL
*   OUT   CTIME     TEMPS DE L'EXECUTION DU TRAVAIL
*   IN    TNAME     NOM DU TRAVAIL (FOURNI PAR L'USAGER)
*
*MODULES
*     GETENVC, IDATE
*
**
      INTEGER        IMON, IDAY, IYEAR
      CHARACTER * 24 FDATE, FULLDAT
      CHARACTER * 8  TIME
      INTEGER IDAT(3)
*
#include "params.cdk"
#include "lnkpak.cdk"
#include "mesgid.cdk"
*
      MESSAGE = ' '
      CALL GETENVC('USER',USAGER)
      JOBN    = USAGER
      FULLDAT = FDATE()
      CALL IDATE(IDAT)
      IDAY = IDAT(1)
      IMON = IDAT(2)
      IYEAR = IDAT(3)
*     CALL IDATE(IMON, IDAY, IYEAR)
      WRITE(CDATE,55) IMON,'/',IDAY,'/',MOD(IYEAR,100)
 55   FORMAT(I2.2, A1, I2.2, A1, I2.2)
      CTIME = FULLDAT(12:19)
      IF(TNAME   .NE. ' ')    JOBN = TNAME
      IF(PROTOCL .EQ. 'LINK') WRITE(MESSAGE,'(4A8)') USAGER, JOBN,
     +   CDATE, CTIME

      WRITE(IPUNIT,'(///T30,"IDENTIFICATION")')
      WRITE(IPUNIT,'(/T10,A8)')  USAGER
      WRITE(IPUNIT,'(/T10,A8)')  JOBN
      WRITE(IPUNIT,'(/T10,A15)') FULLDAT(1:11)//FULLDAT(21:24)
      WRITE(IPUNIT,'(/T10,A8)')  CTIME
      IF (PROTOCL .EQ. 'KMW') WRITE(99,77) USAGER, JOBN, CDATE, CTIME
 77   FORMAT(8X, A8, 8X, A8, 8X, A10, 8X, A8)

      RETURN
      END
#endif
#endif
