#if defined (RASTER) 
***S/P TTTERFI INSTRUCTION DE REMPLISSAGE DE POLYGONES
#include "aaaamac.cdk"
*
      SUBROUTINE TTTERFI( INDIC )
#include "impnone.cdk"
      INTEGER INDIC
*
*AUTEUR   M.VALIN   JAN 1984
*
*REVISION 001 Y. BOURASSA - MAI 94 RATFOR @ FTN77
*
*OBJET(TTTERFI)
*         PREPARER L'APPEL AU SOUS-PROGRAMME DE REMPLISSAGE
*         PROPREMENT DIT EN FAISANT LA TRANSFORMATION DE X-Y A U-V.
*         L'INDICATEUR EFFACEMENT/REMPLISSAGE (INDIC) EST SIMPLEMENT
*         PASSE A TTTTONE
*
*ARGUMENTS
*  IN     INDIC     > 0 REMPLISSAGE
*                   < 0 EFFACEMENT
*
*IMPLICITES
#include "params.cdk"
#include "mapvar.cdk"
*
*NOTES    A CAUSE DE LA LIMITE DE 255 BYTES PAR INSTRUCTION
*         MULTIBYTE, ON NE PEUT PAS AVOIR PLUS DE 63 SOMMETS DANS
*         LE POLYGONE, CAR CHAQUE SOMMET UTILISE 4 BYTES.
*
*MODULE
      EXTERNAL TTTTONE
*
**
      INTEGER  LENG, NCORD, I

#include "mapping.cdk"
*
      LENG = IAND(255 ,BPAIRS(1))   ! EXTRAIRE LES 6 BITS DU BAS

      IF(IAND(LENG,3).NE.0) THEN   ! LONGUEUR PAS UN MULTIPLE DE 4 BYTES
         WRITE(IPUNIT,*)'*** MAUVAISE LONGUEUR - TTTERFI ***'
         RETURN                    ! IGNORER L'INSTRUCTION
      ENDIF

      NCORD = ISHFT(LENG, -1)   ! NOMBRE DE PAIRES DE BYTES
      DO 10 I=1,NCORD,2         ! TRANSFORMATION X-Y  A  U-V
         BPAIRS(I)   = MAPU(IAND(32767, BPAIRS(I+1)),
     +                      IAND(32767, BPAIRS(I+2)))
         BPAIRS(I+1) = MAPV(IAND(32767, BPAIRS(I+1)),
     +                      IAND(32767, BPAIRS(I+2)))
 10      CONTINUE

      NCORD = ISHFT(NCORD, -1)            ! NOMBRE DE PAIRES DE COORDONNEES
      CALL TTTTONE(BPAIRS, NCORD, INDIC)  ! FAIRE REMPLIR LES POLYGONES

      RETURN
      END
#endif
