#!/bin/ksh

set -x

export PKG_VERNO="1.2"
export PKG_VER="gdb-$PKG_VERNO"
export PKG_UPDATE="01-02-2011"
export PKG_SSMVER=gdb_$PKG_VERNO

mtype=`uname -s`
case  $mtype  in
IRIX64 ) export HOSTTYPE=irix65-mipsn32 ;;
Linux  ) rel=`cat /proc/version | awk '{split($3,a,"."); b=a[1]a[2]; print b; }'`;
         export HOSTTYPE=linux$rel-`uname -m | sed 's/_/-/'` ;;
esac
export OS=$HOSTTYPE

PKGDIR=./package/${PKG_VER}
rm -rf ${PKGDIR}
if [ ! -d ${PKGDIR} ]; 
then
	mkdir -p ${PKGDIR}
	mkdir -p ${PKGDIR}/bin
fi

cp -r ./lib ${PKGDIR}
cp -r ./include ${PKGDIR}

cp -r ./etc ${PKGDIR}
cp -r .ssm.d ${PKGDIR}
cat >> ${PKGDIR}/.ssm.d/control << EOF
Package: gdb
Version: ${PKG_VERNO}
Platform: ${HOSTTYPE}
Maintainer: Vanh.Souvanlasy@ec.gc.ca
BuildInfo: ${PKG_UPDATE}
Description: CMDS Geography Database Library for Developpers
EOF

#
# tar
#
cd package
 UDS="_"
 PKG_FN=$PKG_SSMVER$UDS$OS
 mv $PKG_VER $PKG_FN

 tar -cvf $PKG_FN.tar $PKG_FN
 gzip $PKG_FN.tar
 mv $PKG_FN.tar.gz $PKG_FN.ssm
 echo "Removing: $PKG_FN"
 rm -r -f ./$PKG_FN
