*/* RMNLIB - Library of useful routines for C and FORTRAN programming
* * Copyright (C) 1975-2001  Division de Recherche en Prevision Numerique
* *                          Environnement Canada
* *
* * This library is free software; you can redistribute it and/or
* * modify it under the terms of the GNU Lesser General Public
* * License as published by the Free Software Foundation,
* * version 2.1 of the License.
* *
* * This library is distributed in the hope that it will be useful,
* * but WITHOUT ANY WARRANTY; without even the implied warranty of
* * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* * Lesser General Public License for more details.
* *
* * You should have received a copy of the GNU Lesser General Public
* * License along with this library; if not, write to the
* * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
* * Boston, MA 02111-1307, USA.
* */
*
***S/P XEZY        ENSEMBLE DE ROUTINES POUR TRACER ET ANNOTER DES
*                 COURBES
*
      SUBROUTINE XEZY (Y,NPTS,LABGG)
      IMPLICIT NONE
*
*AUTEUR   SYSTEME NCAR
*
*REVISION 001  RPN  M.VALIN / C.THIBEAULT  1-7-78  REFAIT DOCUMENTATION
*
*LANGAGE  FORTRAN
*
*ENTREE   EZY     TRACE UNE COURBE. VARIABLE Y POINTE EN FONCTION DE
*                 SON INDICE
*
*ENTREE   EZXY    TRACE UNE COURBE. VARIABLE Y POINTE EN FONCTION DE LA
*                 VARIABLE X
*
*ENTREE   EZMY    TRACE PLUSIEURS COURBES. VARIABLE Y POINTE EN
*                 FONCTION DE SON PREMIER INDICE
*
*ENTREE   EZMXY   TRACE PLUSIEURS COURBES. VARIABLE Y POINTE EN
*                 FONCTION DE LA VARIABLE X
*
*OBJET(EZY)
*         EZY PERMET DE TRACER UNE COURBE.  L'USAGER DOIT FOURNIR
*                 LE TITRE POUR LE GRAPHIQUE
*
*DIRECTIVES(EZY)
*
*LIBRAIRIES
*         SOURCE  NEWAUTOGRAPHPL,ID=CMCULIB    DECKS=EZY,EZXY,EZMY,EZMX
*
*         OBJET   NCARSYSOB,ID=CMCULIB
*
*ARGUMENTS
*         X       CHAMP DE VARIABLES INDEPENDANTES EMPLOYE SEULEMENT
*                 QUAND IL EST MENTIONNE EXPLICITEMENT DANS L'APPEL
*                 ON PEUT AVOIR UN CHAMP DE X OU PLUSIEURS CHAMPS DE
*                 X POUR PLUSIEURS CHAMPS DE Y
*
*         Y       CHAMP DE VARIABLES A TRACER.  S'IL Y A PLUSIEURS
*                 COURBES, Y A DEUX DIMENSIONS (I.E.  Y(I,J),I=1,2,...
*                 NPTS ET POUR J=1,2,...MANY COURBES.  L'ORDRE DES
*                 INDICES PEUT ETRE RENVERSE (VOIR L'OPTION IROW DANS
*                 CALL DISPLA(LFRAME,IROW,LTYPE)
*
*         L       EST LA LONGUEUR DU PREMIER INDICE DU CHAMP Y LORSQU'O
*                 PARLE D'UN GRAPHIQUE A PLUSIEURS COURBES.
*                 CECI S'APPLIQUE AUSSI POUR X LORSQU'IL A DEUX
*                 DIMENSIONS QUAND ON TRAITE LE CHAMP AU COMPLET
*                 L=NPTS.  NOTE: (L DOIT TOUJOURS ETRE  .GE. NPTS)
*         MANY    NOMBRE DE COURBES A TRACER DU CHAMP Y
*
*         NPTS    NOMBRE DE POINTS POUR CHAQUE COURBE
*
*         LABG    TITRE DU GRAPHIQUE DE 40 CARACTERES OU MOINS.  SI
*                 MOINS DE 40, ON TERMINE LA CHAINE AVEC UN $
*                 NOTE: (LE SYMBOLE $ N'EST PAS POINTE ET LA CHAINE
*                 DE CARACTERES EST AUTOMATIQUEMENT CENTREE.  SI
*                 LABG = 0 LE TITRE DEMEURE BLANC)
*
*IMPLICITES
      INTEGER IBAC,ISET,NDASH,LFRAME,IROW,LTYPE,LNDASH
      COMMON /XAUTOG1/ IBAC,ISET,NDASH,LFRAME,IROW,LTYPE,LNDASH(26)
      CHARACTER(LEN=40) LABX,LABY,LTIT
      CHARACTER(LEN=16) LDASHC(26)
      CHARACTER(LEN=10) LSYM(26)
      CHARACTER(LEN=8)  IFMTX,IFMTY
      COMMON /XAUTOG3/ LABX,LABY,LTIT,LDASHC,LSYM,IFMTX,IFMTY
*
*         LABX    TITRE POUR L'AXE X
*
*         LABY    TITRE POUR L'AXE Y
*
*         LABG    TITRE DU GRAPHIQUE INITIALISE AVEC DES BLANCS
*
*         IBAC    INDICATEUR QUI DETERMINE LE FOND A UTILISE
*
*         ISET    CONTROLE L'ECHELLE
*
*         NDASH   CONTROLE LE PATRON DES LIGNES A TRACER
*
*         LDASH   CHAMP DES PATRONS A TRACER
*
*         LFRAME  CONTROLE L'AVANCE DE L'IMAGE
*
*         IROW    INDIQUE LA FACON D'ENREGISTRER LE DATA DANS LES
*                 CHAMPS X ET Y
*
*         LTYPE   CONTROLE LA PRESENTATION DE LA COURBE
*
*         LTIT    TITRE DU GRAPHIQUE
*
*
*         *** VOIR ROUTINE PLOT80 POUR PLUS DE DETAIL SUR LA DESCRIPTIO
*             DE AUTOG1 ***
*
*MODULES  SWAPHD,PLOT80
*
*PRECISION
*         SIMPLE
*
*ALGORITHME
*         LES COURBES SONT TRACEES POINT PAR POINT AVEC LA ROUTINE VECT
*
*----------------------------------------------------------------------
*
      INTEGER IHGP,IXGRD,L,NC,NPTS,NSET,NX,NY
      REAL   Y(1), X
      CHARACTER(LEN=*) LABGG
      EXTERNAL PLOT80
*
*----------------------------------------------------------------------
*
*     POUR UNE COURBE, IROW DOIT ETRE POSITIF (I.E. --COL.  ENTREE)
*
      IF (IROW .LT. 0) IROW = -IROW
*
*     IABS(IXGRD) = 1   PAS DE CHAMP X
*
      IXGRD = 1
*
*     IXGRD DOIT ETRE NEGATIF SI LE DATA EST ENREGISTRE PAR RANGEE
*       (IROW.LT.0)
*
      IF (IROW .LT. 0) IXGRD = -IXGRD
*
*     PREPARATION POUR UNE COURBE
*
      L = NPTS
      NX = 1
      NY = 1
      NC = 1
*
*     LABG CONTIENT LE TITRE DU GRAPHIQUE INITIALIZE PAR DEFAUT.  SI
*       LABGG .NE. 0 LE TITRE DONNE PAR L'USAGER VA DANS LTIT
*
      IF (LABGG .NE. ' ')  THEN
        LTIT = LABGG
      ELSE
        LTIT = '$'
      ENDIF
*
*     PREPARATION POUR LE FOND (GRIDAL ET LES TITRES)
*       ISET  CONTROLE L'APPEL A SET
*       NSET  CONTROLE L'ENSEMBLE DE LA LOGIQUE (FOND, TITRE ET COURBE)
*       IHGP  CONTROLE L'APPEL A GRIDAL
*
      IF (ISET .GT. 0) GO TO 101
      NSET = -2
      IHGP = 2-IBAC
      GO TO 102
  101 NSET = 3
      IF (IBAC .LT. 4) NSET = 0
      IHGP = 2-IBAC
      GO TO 102
  102 CONTINUE
*
*
      CALL XPLOT80 (X,Y,NPTS,NC,L,NX,NY,IXGRD,LTIT,NDASH,
     1             NSET,IHGP,ISET,LTYPE,LFRAME)
*
      RETURN
      END
