***S/P  TTTPCAR - FAIRE TRACER LE CARACTERE DEMANDE PAR PWRY
#include "aaaamac.cdk"
*
      SUBROUTINE  TTTPCAR(CHARA, IFNT, INTEN, MODE, IX, IY, PASSE)
#include "impnone.cdk"
      INTEGER             CHARA, IFNT, INTEN, MODE, IX, IY, PASSE
*
*AUTEUR   - M.VALIN
*
*REVISION 001  A. COTE NOV,78 ENHANCE, NOENHAN, CLRPRNT, NOCLRPR
*         002          NOV,83
*         003  Y. BOURASSA - MAI 94 RATFOR @ FTN77
*
*LANGUAGE   - FTN77
*
*LANGAGE  - RATFOR
*
*OBJET(TTTPCAR)
*         - TTTPCAR FAIT TRACER UN CARACTERE EN TENANT COMPTE DE
*           L'ORIENTATION
*           SI ON DESIRE TRACER BLANC SUR NOIR,TTTPCAR GENERERA
*           LE CONTOUR FONCE PUIS FERA TRACER LE CARACTERE.
*
*
*MESSAGES - SUR IMPRIMANTE
*               "****THE FONT;   OF CHARACTR;   UNDEFINED ...IGNORED"
*
*ARGUMENTS
*         - CHARA - CARACTERE A TRACER (EN DISPLAY CODE)
*         - IFNT  - SORTE DE CARACTERE(0-8)
*         - INTEN - INTENSITE
*         - MODE  - MODE DE DESSIN (VOIR MODLIN/MODCAR DANS LE BLOC PARAMS)
*         - IX,IY - COORDONNEES DU PREMIER POINT DU CARACTERE
*
*IMPLICITES
#include "pwryp.cdk"
#include "params.cdk"
#include "carac.cdk"
#include "mapvar.cdk"
*
**INTERNE
*
*
*TABLES   - ICHAR - TABLES CONTENANT LES COORDONNEES POUR TRACER LES
*                   CARACTERES
*         - IVP   - TABLES DES POINTEURS VERS LE CARACTERE DEMANDE DANS ICHAR
*
*----------------------------------------------------------------------
*
*MODULE
      EXTERNAL TTTXTRC
      INTEGER  TTTXTRC
*
**
      INTEGER  IREF,  ICP, IDX, IDY
      REAL     OLDC1, BSX, BSY, OLDC2, RX, RY

#include "mapping.cdk"

*     ON RETIENT LE POINT D'ORIGINE DU CARACTERE CAR LES COORDONNEES
*     EXTRAITES SONT RELATIVES.

      BSX   = FLOAT(IX)
      BSY   = FLOAT(IY)
      OLDC1 = C1
      OLDC2 = C2
      C1    = C1 + 0.125 - MOD(RMAPU(BSX,BSY),0.25)
      C2    = C2 + 0.125 - MOD(RMAPV(BSX,BSY),0.25)

*     ON SE PREPARE A TRACER LES CARACTERE.
*
*     POUR TROUVER LE CARACTERE DEMANDE, ON SE SERT DE IVP ; POINTEUR VERS
*     LE CARACTERE DEMANDE
*
*     IVP EST ORGANISE DE LA FACON SUIVANTE; IVP(I,J)
*
*             I=1,2  ; POUR LE CARACTERE SPECIFIE, POINTE VERS TOUTE SES FONTES
*                      5 FONTES PAR I CONSTRUITE A RAISON DE 12 BITS PAR FONTE
*                      CES 12 BITS CONTENANT L'INDEX DE ICHAR CORRESPONDANT
*                      A CETTE FONTE.
*
*             J=1,32:95 ; LE DISPLAY CODE DU CARACTERE DEMANDE  NOUS DONNE LE
*                      J DESIRE.
      IREF = IVP(IFNT, CHARA)

      IF(IREF .EQ. 0) THEN
*        FONTE INCONNUE
         WRITE(6,600) IFNT, CHARA
*        UTILISER OBLIQUE ARRIERE POUR CARACTERE NON DEFINI
         IREF = IVP(0,92)
      ENDIF

*     ON VA CHERCHER AVEC TTTXTRC LA VARIATION EN X ET EN Y A DONNER POUR
*     TRACER CHAQUE TRAIT QUI TOUS ENSEMBLE DONNE LE CARACTERE.*
 10   IF(ICHAR(IREF) .NE. -1) THEN
         ICP = IAND(ISHFT(ICHAR(IREF),-13),  7)
         IDX = IAND(ISHFT(ICHAR(IREF), -7), 63)
         IDY = IAND(ICHAR(IREF), 127)
         IDY = IDY - 16
         RX  = BSX+IDX*X1+IDY*X2
         RY  = BSY+IDX*Y1+IDY*Y2
         IF(PASSE .EQ.3) CALL TTTDRAW(RX, RY, ICP, INTEN, MODE)
         IREF = IREF + 1        ! ON CHANGE DE SERIES DE BITS
         GO TO 10
      ENDIF
      IF(PASSE .NE. 3) CALL TTTDRAW(RX, RY, 0, INTEN, MODE)
      C1 = OLDC1
      C2 = OLDC2

      RETURN
 600  FORMAT('0',20X,'**** FONT ',I2,' OF CHARACTR ',I3,
     +       '  UNDEFINED ...IGNORED')
      END
