float c_wglasx(char *string, int stringLength);
float c_wgldsx(char *string, int stringLength);
float c_wglhsx(char *string, int stringLength);
float c_wglwsx(char *string, int stringLength);
int  c_wglasi(char *string, int stringLength);
int  c_wgldsi(char *string, int stringLength);
int  c_wglhsi(char *string, int stringLength);
int  c_wglpsx(float x, float y, char *string, int stringLength, int size, int orient, int codeCentrage);
int  c_wglwsi(char *string, int stringLength);
int c_wglafi(int i, int j, int rayon, float angleDebut, float angleFin);
int c_wglafx(float x, float y, float rayon, float angleDebut, float angleFin);
int c_wglali(int i, int j, int rayon, float angleDebut, float angleFin);
int c_wglalx(float x, float y, float rayon, float angleDebut, float angleFin);
int c_wglbbf();
int c_wglbrb();
int c_wglbti(int *i, int *j);
int c_wglbtn(int bouton);
int c_wglbtp(int bouton);
int c_wglbtpi(int bouton, int *i, int *j);
int c_wglbtpx(int bouton, float *x, float *y);
int c_wglbtx(float *x, float *y);
int c_wglcfi(int i, int j, int rayon);
int c_wglcfx(float x, float y, float rayon);
int c_wglcli(int i, int j, int rayon);
int c_wglclr();
int c_wglclw(int indFenetre);
int c_wglclx(float x, float y, float rayon);
int c_wglcmi(int left, int bottom, int right, int top);
int c_wglcmx(float left, float bottom, float right, float top);
int c_wglcol(int couleur);
int c_wglcrb(int couleur);
int c_wgldbf();
int c_wgldbg();
int c_wgldcm();
int c_wgldld(int indDash, int dashPattern);
int c_wgldpt(int indpat, int ipatsz, char iptrn[]);
int c_wgldri(int i, int j);
int c_wgldrx(float x, float y);
int c_wglecr(char *nomFenetre);
int c_wglerb();
int c_wglfbf();
int c_wglfsc();
int c_wglfsh();
int c_wglfshlb();
int c_wglfsz(int fontSize);
int c_wglfsz(int fontSize);
int c_wglgacw();
int c_wglgaf();
int c_wglgbf();
int c_wglgci();
int c_wglgco(int indCol, int *red, int *green, int *blue);
int c_wglgdbg();
int c_wglgetcmap(int *colormap);
int c_wglgld();
int c_wglglpti(int *ix, int *iy);
int c_wglglw();
int c_wglgmk();
int c_wglgmod();
int c_wglgpl();
int c_wglgpt();
int c_wglgsi(int *idebut, int *jdebut, int *ifin, int *jfin);
int c_wglgsp(float *xdebut, float *ydebut, float *xfin, float *yfin, int   *idebut, int *jdebut, int *ifin, int *jfin);
int c_wglgsx(float *xdebut, float *ydebut, float *xfin, float *yfin);
int c_wglgvi(int *idebut, int *jdebut, int *ifin, int *jfin);
int c_wglgvp(float *xdebut, float *ydebut, float *xfin, float *yfin, int *idebut, int *jdebut, int *ifin, int *jfin);
int c_wglgvx(float *xdebut, float *ydebut, float *xfin, float *yfin);
int c_wglgwz(int *isize, int *jsize);
int c_wglgzi(int *isize, int *jsize);
int c_wglgzp(float *xsize, float *ysize, int *isize, int *jsize);
int c_wglgzx(float *xsize, float *ysize);
int c_wglias(int flagAspect);
int c_wgliax(float *x, float *y, int i, int j);
int c_wglinit();
int c_wglinstcmap();
int c_wglkas(int xAspect, int yAspect);
int c_wgllpt();
int c_wgllwi(int lineWidth);
int c_wglmco(int couleur, int r, int g, int b);
int c_wglmcos(int couleurs[], int nbCols, int rgbDefs[][3]);
int c_wglmcw(int couleur, int r, int g, int b);
int c_wglmvi(int i, int j);
int c_wglmvx(float x, float y);
int c_wglncl(int *ncolRead, int *ncolWrite, int *ncolAnim);
int c_wglopmw(char *nomFenetre, int wglWinID);
int c_wglopw(char *nomFenetre);
int c_wglpfi(int nbPoints, int polygone[][2]);
int c_wglpfx(int nbPoints, float polygone[][2]);
int c_wglpli (int nbPoints, int polygone[][2]);
int c_wglplx(int nbPoints, float polygone[][2]);
int c_wglppo(int ix, int iy, int isize, int jsize);
int c_wglpsi(int i, int j, char *string, int stringLength, int size, int orient, int codeCentrage);
int c_wglpsi(int i, int j, char *string, int stringLength, int size, int orient, int codeCentrage);
int c_wglpsz(int isize, int jsize);
int c_wglpti(int i, int j);
int c_wglptis(wgl_point pts[], int npts);
int c_wglptx(float x, float y);
int c_wglptxs(float *xxx, float *yyy, int *npts);
int c_wglrfi(int ia, int ja, int ib, int jb);
int c_wglrfx(float xa, float ya, float xb, float yb);
int c_wglrli(int ia, int ja, int ib, int jb);
int c_wglrlx(float xa, float ya, float xb, float yb);
int c_wglroc();
int c_wglrwc();
int c_wglsbf();
int c_wglscon(char *contexte);
int c_wglscon_x();
int c_wglsetw(int winid);
int c_wglsetwcmap();
int c_wglsld(int indDash);
int c_wglsmk(int masque);
int c_wglspt(int indpat);
int c_wglstu(int istep, int jstep);
int c_wglswb();
int c_wglxai(int *i, int *j, float x, float y);
unsigned int c_wglcolf(float couleur);
unsigned int c_wglcolfs(float *cols, unsigned int *pixels, int n);
unsigned int c_wglcolfs_fst(float *cols, unsigned int *pixels, int n);
void c_wglssp(float xdebut, float ydebut, float xfin, float yfin, int idebut, int jdebut, int ifin, int jfin, int mode);
void c_fxfy2xy(float *x, float *y, float fx, float fy);
void c_vfxfy2xy(float *x, float *y, float *fx, float *fy, int npts);
void c_vxy2fxfy(float *fx, float *fy, float *x, float *y, int npts);
void c_xsetxy(int mode, float *tx, int nx, float *ty, int ny);
void c_xy2fxfy(float *fx, float *fy, float x, float y);
void f77name(fxfy2xy)(float *x, float *y, float *fx, float *fy);
void f77name(vfxfy2xy)(float *x, float *y, float *fx, float *fy, int *npts);
void f77name(vxy2fxfy)(float *fx, float *fy, float *x, float *y, int *npts);
void f77name(xsetxy)(int *mode, float *tx, int *nx, float *ty, int *ny);
void f77name(xy2fxfy)(float *fx, float *fy, float *x, float *y);
